// code by jph
package ch.alpine.tensor.lie;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

enum TestHelper {
  INSTANCE;

  final List<List<List<Integer>>> LIST = new ArrayList<>();

  TestHelper() {
    {
      LIST.add(Arrays.asList( //
          Arrays.asList()));
    }
    // ---
    {
      LIST.add(Arrays.asList( //
          Arrays.asList(0)));
    }
    // ---
    {
      LIST.add(Arrays.asList( //
          Arrays.asList(0, 1), //
          Arrays.asList(1, 0)));
    }
    // ---
    {
      LIST.add(Arrays.asList( //
          Arrays.asList(0, 1, 2), //
          Arrays.asList(0, 2, 1), //
          Arrays.asList(1, 0, 2), //
          Arrays.asList(1, 2, 0), //
          Arrays.asList(2, 0, 1), //
          Arrays.asList(2, 1, 0)));
    }
    // ---
    {
      LIST.add(Arrays.asList( //
          Arrays.asList(0, 1, 2, 3), //
          Arrays.asList(0, 1, 3, 2), //
          Arrays.asList(0, 2, 1, 3), //
          Arrays.asList(0, 2, 3, 1), //
          Arrays.asList(0, 3, 1, 2), //
          Arrays.asList(0, 3, 2, 1), //
          Arrays.asList(1, 0, 2, 3), //
          Arrays.asList(1, 0, 3, 2), //
          Arrays.asList(1, 2, 0, 3), //
          Arrays.asList(1, 2, 3, 0), //
          Arrays.asList(1, 3, 0, 2), //
          Arrays.asList(1, 3, 2, 0), //
          Arrays.asList(2, 0, 1, 3), //
          Arrays.asList(2, 0, 3, 1), //
          Arrays.asList(2, 1, 0, 3), //
          Arrays.asList(2, 1, 3, 0), //
          Arrays.asList(2, 3, 0, 1), //
          Arrays.asList(2, 3, 1, 0), //
          Arrays.asList(3, 0, 1, 2), //
          Arrays.asList(3, 0, 2, 1), //
          Arrays.asList(3, 1, 0, 2), //
          Arrays.asList(3, 1, 2, 0), //
          Arrays.asList(3, 2, 0, 1), //
          Arrays.asList(3, 2, 1, 0)));
    }
    // ---
    {
      List<List<Integer>> list = new ArrayList<>();
      list.add(Arrays.asList(0, 1, 2, 3, 4));
      list.add(Arrays.asList(0, 1, 2, 4, 3));
      list.add(Arrays.asList(0, 1, 3, 2, 4));
      list.add(Arrays.asList(0, 1, 3, 4, 2));
      list.add(Arrays.asList(0, 1, 4, 2, 3));
      list.add(Arrays.asList(0, 1, 4, 3, 2));
      list.add(Arrays.asList(0, 2, 1, 3, 4));
      list.add(Arrays.asList(0, 2, 1, 4, 3));
      list.add(Arrays.asList(0, 2, 3, 1, 4));
      list.add(Arrays.asList(0, 2, 3, 4, 1));
      list.add(Arrays.asList(0, 2, 4, 1, 3));
      list.add(Arrays.asList(0, 2, 4, 3, 1));
      list.add(Arrays.asList(0, 3, 1, 2, 4));
      list.add(Arrays.asList(0, 3, 1, 4, 2));
      list.add(Arrays.asList(0, 3, 2, 1, 4));
      list.add(Arrays.asList(0, 3, 2, 4, 1));
      list.add(Arrays.asList(0, 3, 4, 1, 2));
      list.add(Arrays.asList(0, 3, 4, 2, 1));
      list.add(Arrays.asList(0, 4, 1, 2, 3));
      list.add(Arrays.asList(0, 4, 1, 3, 2));
      list.add(Arrays.asList(0, 4, 2, 1, 3));
      list.add(Arrays.asList(0, 4, 2, 3, 1));
      list.add(Arrays.asList(0, 4, 3, 1, 2));
      list.add(Arrays.asList(0, 4, 3, 2, 1));
      list.add(Arrays.asList(1, 0, 2, 3, 4));
      list.add(Arrays.asList(1, 0, 2, 4, 3));
      list.add(Arrays.asList(1, 0, 3, 2, 4));
      list.add(Arrays.asList(1, 0, 3, 4, 2));
      list.add(Arrays.asList(1, 0, 4, 2, 3));
      list.add(Arrays.asList(1, 0, 4, 3, 2));
      list.add(Arrays.asList(1, 2, 0, 3, 4));
      list.add(Arrays.asList(1, 2, 0, 4, 3));
      list.add(Arrays.asList(1, 2, 3, 0, 4));
      list.add(Arrays.asList(1, 2, 3, 4, 0));
      list.add(Arrays.asList(1, 2, 4, 0, 3));
      list.add(Arrays.asList(1, 2, 4, 3, 0));
      list.add(Arrays.asList(1, 3, 0, 2, 4));
      list.add(Arrays.asList(1, 3, 0, 4, 2));
      list.add(Arrays.asList(1, 3, 2, 0, 4));
      list.add(Arrays.asList(1, 3, 2, 4, 0));
      list.add(Arrays.asList(1, 3, 4, 0, 2));
      list.add(Arrays.asList(1, 3, 4, 2, 0));
      list.add(Arrays.asList(1, 4, 0, 2, 3));
      list.add(Arrays.asList(1, 4, 0, 3, 2));
      list.add(Arrays.asList(1, 4, 2, 0, 3));
      list.add(Arrays.asList(1, 4, 2, 3, 0));
      list.add(Arrays.asList(1, 4, 3, 0, 2));
      list.add(Arrays.asList(1, 4, 3, 2, 0));
      list.add(Arrays.asList(2, 0, 1, 3, 4));
      list.add(Arrays.asList(2, 0, 1, 4, 3));
      list.add(Arrays.asList(2, 0, 3, 1, 4));
      list.add(Arrays.asList(2, 0, 3, 4, 1));
      list.add(Arrays.asList(2, 0, 4, 1, 3));
      list.add(Arrays.asList(2, 0, 4, 3, 1));
      list.add(Arrays.asList(2, 1, 0, 3, 4));
      list.add(Arrays.asList(2, 1, 0, 4, 3));
      list.add(Arrays.asList(2, 1, 3, 0, 4));
      list.add(Arrays.asList(2, 1, 3, 4, 0));
      list.add(Arrays.asList(2, 1, 4, 0, 3));
      list.add(Arrays.asList(2, 1, 4, 3, 0));
      list.add(Arrays.asList(2, 3, 0, 1, 4));
      list.add(Arrays.asList(2, 3, 0, 4, 1));
      list.add(Arrays.asList(2, 3, 1, 0, 4));
      list.add(Arrays.asList(2, 3, 1, 4, 0));
      list.add(Arrays.asList(2, 3, 4, 0, 1));
      list.add(Arrays.asList(2, 3, 4, 1, 0));
      list.add(Arrays.asList(2, 4, 0, 1, 3));
      list.add(Arrays.asList(2, 4, 0, 3, 1));
      list.add(Arrays.asList(2, 4, 1, 0, 3));
      list.add(Arrays.asList(2, 4, 1, 3, 0));
      list.add(Arrays.asList(2, 4, 3, 0, 1));
      list.add(Arrays.asList(2, 4, 3, 1, 0));
      list.add(Arrays.asList(3, 0, 1, 2, 4));
      list.add(Arrays.asList(3, 0, 1, 4, 2));
      list.add(Arrays.asList(3, 0, 2, 1, 4));
      list.add(Arrays.asList(3, 0, 2, 4, 1));
      list.add(Arrays.asList(3, 0, 4, 1, 2));
      list.add(Arrays.asList(3, 0, 4, 2, 1));
      list.add(Arrays.asList(3, 1, 0, 2, 4));
      list.add(Arrays.asList(3, 1, 0, 4, 2));
      list.add(Arrays.asList(3, 1, 2, 0, 4));
      list.add(Arrays.asList(3, 1, 2, 4, 0));
      list.add(Arrays.asList(3, 1, 4, 0, 2));
      list.add(Arrays.asList(3, 1, 4, 2, 0));
      list.add(Arrays.asList(3, 2, 0, 1, 4));
      list.add(Arrays.asList(3, 2, 0, 4, 1));
      list.add(Arrays.asList(3, 2, 1, 0, 4));
      list.add(Arrays.asList(3, 2, 1, 4, 0));
      list.add(Arrays.asList(3, 2, 4, 0, 1));
      list.add(Arrays.asList(3, 2, 4, 1, 0));
      list.add(Arrays.asList(3, 4, 0, 1, 2));
      list.add(Arrays.asList(3, 4, 0, 2, 1));
      list.add(Arrays.asList(3, 4, 1, 0, 2));
      list.add(Arrays.asList(3, 4, 1, 2, 0));
      list.add(Arrays.asList(3, 4, 2, 0, 1));
      list.add(Arrays.asList(3, 4, 2, 1, 0));
      list.add(Arrays.asList(4, 0, 1, 2, 3));
      list.add(Arrays.asList(4, 0, 1, 3, 2));
      list.add(Arrays.asList(4, 0, 2, 1, 3));
      list.add(Arrays.asList(4, 0, 2, 3, 1));
      list.add(Arrays.asList(4, 0, 3, 1, 2));
      list.add(Arrays.asList(4, 0, 3, 2, 1));
      list.add(Arrays.asList(4, 1, 0, 2, 3));
      list.add(Arrays.asList(4, 1, 0, 3, 2));
      list.add(Arrays.asList(4, 1, 2, 0, 3));
      list.add(Arrays.asList(4, 1, 2, 3, 0));
      list.add(Arrays.asList(4, 1, 3, 0, 2));
      list.add(Arrays.asList(4, 1, 3, 2, 0));
      list.add(Arrays.asList(4, 2, 0, 1, 3));
      list.add(Arrays.asList(4, 2, 0, 3, 1));
      list.add(Arrays.asList(4, 2, 1, 0, 3));
      list.add(Arrays.asList(4, 2, 1, 3, 0));
      list.add(Arrays.asList(4, 2, 3, 0, 1));
      list.add(Arrays.asList(4, 2, 3, 1, 0));
      list.add(Arrays.asList(4, 3, 0, 1, 2));
      list.add(Arrays.asList(4, 3, 0, 2, 1));
      list.add(Arrays.asList(4, 3, 1, 0, 2));
      list.add(Arrays.asList(4, 3, 1, 2, 0));
      list.add(Arrays.asList(4, 3, 2, 0, 1));
      list.add(Arrays.asList(4, 3, 2, 1, 0));
      LIST.add(Collections.unmodifiableList(list));
    }
    // ---
    {
      List<List<Integer>> list = new ArrayList<>();
      list.add(Arrays.asList(new Integer[] { 0, 1, 2, 3, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 2, 3, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 2, 4, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 2, 4, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 2, 5, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 2, 5, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 3, 2, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 3, 2, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 3, 4, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 3, 4, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 3, 5, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 3, 5, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 4, 2, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 4, 2, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 4, 3, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 4, 3, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 4, 5, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 4, 5, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 5, 2, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 5, 2, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 5, 3, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 5, 3, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 5, 4, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 1, 5, 4, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 1, 3, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 1, 3, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 1, 4, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 1, 4, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 1, 5, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 1, 5, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 3, 1, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 3, 1, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 3, 4, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 3, 4, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 3, 5, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 3, 5, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 4, 1, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 4, 1, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 4, 3, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 4, 3, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 4, 5, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 4, 5, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 5, 1, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 5, 1, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 5, 3, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 5, 3, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 5, 4, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 2, 5, 4, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 1, 2, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 1, 2, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 1, 4, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 1, 4, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 1, 5, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 1, 5, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 2, 1, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 2, 1, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 2, 4, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 2, 4, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 2, 5, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 2, 5, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 4, 1, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 4, 1, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 4, 2, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 4, 2, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 4, 5, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 4, 5, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 5, 1, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 5, 1, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 5, 2, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 5, 2, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 5, 4, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 3, 5, 4, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 1, 2, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 1, 2, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 1, 3, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 1, 3, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 1, 5, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 1, 5, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 2, 1, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 2, 1, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 2, 3, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 2, 3, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 2, 5, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 2, 5, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 3, 1, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 3, 1, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 3, 2, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 3, 2, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 3, 5, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 3, 5, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 5, 1, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 5, 1, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 5, 2, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 5, 2, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 5, 3, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 4, 5, 3, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 1, 2, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 1, 2, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 1, 3, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 1, 3, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 1, 4, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 1, 4, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 2, 1, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 2, 1, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 2, 3, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 2, 3, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 2, 4, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 2, 4, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 3, 1, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 3, 1, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 3, 2, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 3, 2, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 3, 4, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 3, 4, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 4, 1, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 4, 1, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 4, 2, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 4, 2, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 4, 3, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 0, 5, 4, 3, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 2, 3, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 2, 3, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 2, 4, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 2, 4, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 2, 5, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 2, 5, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 3, 2, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 3, 2, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 3, 4, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 3, 4, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 3, 5, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 3, 5, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 4, 2, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 4, 2, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 4, 3, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 4, 3, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 4, 5, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 4, 5, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 5, 2, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 5, 2, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 5, 3, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 5, 3, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 5, 4, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 0, 5, 4, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 0, 3, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 0, 3, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 0, 4, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 0, 4, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 0, 5, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 0, 5, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 3, 0, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 3, 0, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 3, 4, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 3, 4, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 3, 5, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 3, 5, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 4, 0, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 4, 0, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 4, 3, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 4, 3, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 4, 5, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 4, 5, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 5, 0, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 5, 0, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 5, 3, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 5, 3, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 5, 4, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 2, 5, 4, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 0, 2, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 0, 2, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 0, 4, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 0, 4, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 0, 5, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 0, 5, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 2, 0, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 2, 0, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 2, 4, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 2, 4, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 2, 5, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 2, 5, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 4, 0, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 4, 0, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 4, 2, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 4, 2, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 4, 5, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 4, 5, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 5, 0, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 5, 0, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 5, 2, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 5, 2, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 5, 4, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 3, 5, 4, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 0, 2, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 0, 2, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 0, 3, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 0, 3, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 0, 5, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 0, 5, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 2, 0, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 2, 0, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 2, 3, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 2, 3, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 2, 5, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 2, 5, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 3, 0, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 3, 0, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 3, 2, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 3, 2, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 3, 5, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 3, 5, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 5, 0, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 5, 0, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 5, 2, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 5, 2, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 5, 3, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 4, 5, 3, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 0, 2, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 0, 2, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 0, 3, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 0, 3, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 0, 4, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 0, 4, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 2, 0, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 2, 0, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 2, 3, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 2, 3, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 2, 4, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 2, 4, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 3, 0, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 3, 0, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 3, 2, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 3, 2, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 3, 4, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 3, 4, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 4, 0, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 4, 0, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 4, 2, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 4, 2, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 4, 3, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 1, 5, 4, 3, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 1, 3, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 1, 3, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 1, 4, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 1, 4, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 1, 5, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 1, 5, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 3, 1, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 3, 1, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 3, 4, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 3, 4, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 3, 5, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 3, 5, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 4, 1, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 4, 1, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 4, 3, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 4, 3, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 4, 5, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 4, 5, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 5, 1, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 5, 1, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 5, 3, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 5, 3, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 5, 4, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 0, 5, 4, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 0, 3, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 0, 3, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 0, 4, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 0, 4, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 0, 5, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 0, 5, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 3, 0, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 3, 0, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 3, 4, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 3, 4, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 3, 5, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 3, 5, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 4, 0, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 4, 0, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 4, 3, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 4, 3, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 4, 5, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 4, 5, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 5, 0, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 5, 0, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 5, 3, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 5, 3, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 5, 4, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 1, 5, 4, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 0, 1, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 0, 1, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 0, 4, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 0, 4, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 0, 5, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 0, 5, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 1, 0, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 1, 0, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 1, 4, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 1, 4, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 1, 5, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 1, 5, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 4, 0, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 4, 0, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 4, 1, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 4, 1, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 4, 5, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 4, 5, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 5, 0, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 5, 0, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 5, 1, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 5, 1, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 5, 4, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 3, 5, 4, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 0, 1, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 0, 1, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 0, 3, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 0, 3, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 0, 5, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 0, 5, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 1, 0, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 1, 0, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 1, 3, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 1, 3, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 1, 5, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 1, 5, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 3, 0, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 3, 0, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 3, 1, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 3, 1, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 3, 5, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 3, 5, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 5, 0, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 5, 0, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 5, 1, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 5, 1, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 5, 3, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 4, 5, 3, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 0, 1, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 0, 1, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 0, 3, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 0, 3, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 0, 4, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 0, 4, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 1, 0, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 1, 0, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 1, 3, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 1, 3, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 1, 4, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 1, 4, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 3, 0, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 3, 0, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 3, 1, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 3, 1, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 3, 4, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 3, 4, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 4, 0, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 4, 0, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 4, 1, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 4, 1, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 4, 3, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 2, 5, 4, 3, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 1, 2, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 1, 2, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 1, 4, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 1, 4, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 1, 5, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 1, 5, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 2, 1, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 2, 1, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 2, 4, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 2, 4, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 2, 5, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 2, 5, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 4, 1, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 4, 1, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 4, 2, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 4, 2, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 4, 5, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 4, 5, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 5, 1, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 5, 1, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 5, 2, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 5, 2, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 5, 4, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 0, 5, 4, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 0, 2, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 0, 2, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 0, 4, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 0, 4, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 0, 5, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 0, 5, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 2, 0, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 2, 0, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 2, 4, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 2, 4, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 2, 5, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 2, 5, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 4, 0, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 4, 0, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 4, 2, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 4, 2, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 4, 5, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 4, 5, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 5, 0, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 5, 0, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 5, 2, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 5, 2, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 5, 4, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 1, 5, 4, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 0, 1, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 0, 1, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 0, 4, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 0, 4, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 0, 5, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 0, 5, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 1, 0, 4, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 1, 0, 5, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 1, 4, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 1, 4, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 1, 5, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 1, 5, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 4, 0, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 4, 0, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 4, 1, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 4, 1, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 4, 5, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 4, 5, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 5, 0, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 5, 0, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 5, 1, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 5, 1, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 5, 4, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 2, 5, 4, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 0, 1, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 0, 1, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 0, 2, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 0, 2, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 0, 5, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 0, 5, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 1, 0, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 1, 0, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 1, 2, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 1, 2, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 1, 5, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 1, 5, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 2, 0, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 2, 0, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 2, 1, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 2, 1, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 2, 5, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 2, 5, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 5, 0, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 5, 0, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 5, 1, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 5, 1, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 5, 2, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 4, 5, 2, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 0, 1, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 0, 1, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 0, 2, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 0, 2, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 0, 4, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 0, 4, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 1, 0, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 1, 0, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 1, 2, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 1, 2, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 1, 4, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 1, 4, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 2, 0, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 2, 0, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 2, 1, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 2, 1, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 2, 4, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 2, 4, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 4, 0, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 4, 0, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 4, 1, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 4, 1, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 4, 2, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 3, 5, 4, 2, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 1, 2, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 1, 2, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 1, 3, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 1, 3, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 1, 5, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 1, 5, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 2, 1, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 2, 1, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 2, 3, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 2, 3, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 2, 5, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 2, 5, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 3, 1, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 3, 1, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 3, 2, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 3, 2, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 3, 5, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 3, 5, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 5, 1, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 5, 1, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 5, 2, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 5, 2, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 5, 3, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 0, 5, 3, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 0, 2, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 0, 2, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 0, 3, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 0, 3, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 0, 5, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 0, 5, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 2, 0, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 2, 0, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 2, 3, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 2, 3, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 2, 5, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 2, 5, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 3, 0, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 3, 0, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 3, 2, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 3, 2, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 3, 5, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 3, 5, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 5, 0, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 5, 0, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 5, 2, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 5, 2, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 5, 3, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 1, 5, 3, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 0, 1, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 0, 1, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 0, 3, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 0, 3, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 0, 5, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 0, 5, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 1, 0, 3, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 1, 0, 5, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 1, 3, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 1, 3, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 1, 5, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 1, 5, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 3, 0, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 3, 0, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 3, 1, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 3, 1, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 3, 5, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 3, 5, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 5, 0, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 5, 0, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 5, 1, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 5, 1, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 5, 3, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 2, 5, 3, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 0, 1, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 0, 1, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 0, 2, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 0, 2, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 0, 5, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 0, 5, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 1, 0, 2, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 1, 0, 5, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 1, 2, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 1, 2, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 1, 5, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 1, 5, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 2, 0, 1, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 2, 0, 5, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 2, 1, 0, 5 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 2, 1, 5, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 2, 5, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 2, 5, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 5, 0, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 5, 0, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 5, 1, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 5, 1, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 5, 2, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 3, 5, 2, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 0, 1, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 0, 1, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 0, 2, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 0, 2, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 0, 3, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 0, 3, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 1, 0, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 1, 0, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 1, 2, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 1, 2, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 1, 3, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 1, 3, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 2, 0, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 2, 0, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 2, 1, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 2, 1, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 2, 3, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 2, 3, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 3, 0, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 3, 0, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 3, 1, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 3, 1, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 3, 2, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 4, 5, 3, 2, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 1, 2, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 1, 2, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 1, 3, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 1, 3, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 1, 4, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 1, 4, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 2, 1, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 2, 1, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 2, 3, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 2, 3, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 2, 4, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 2, 4, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 3, 1, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 3, 1, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 3, 2, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 3, 2, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 3, 4, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 3, 4, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 4, 1, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 4, 1, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 4, 2, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 4, 2, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 4, 3, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 0, 4, 3, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 0, 2, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 0, 2, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 0, 3, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 0, 3, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 0, 4, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 0, 4, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 2, 0, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 2, 0, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 2, 3, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 2, 3, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 2, 4, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 2, 4, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 3, 0, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 3, 0, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 3, 2, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 3, 2, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 3, 4, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 3, 4, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 4, 0, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 4, 0, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 4, 2, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 4, 2, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 4, 3, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 1, 4, 3, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 0, 1, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 0, 1, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 0, 3, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 0, 3, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 0, 4, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 0, 4, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 1, 0, 3, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 1, 0, 4, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 1, 3, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 1, 3, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 1, 4, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 1, 4, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 3, 0, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 3, 0, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 3, 1, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 3, 1, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 3, 4, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 3, 4, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 4, 0, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 4, 0, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 4, 1, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 4, 1, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 4, 3, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 2, 4, 3, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 0, 1, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 0, 1, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 0, 2, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 0, 2, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 0, 4, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 0, 4, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 1, 0, 2, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 1, 0, 4, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 1, 2, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 1, 2, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 1, 4, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 1, 4, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 2, 0, 1, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 2, 0, 4, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 2, 1, 0, 4 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 2, 1, 4, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 2, 4, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 2, 4, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 4, 0, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 4, 0, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 4, 1, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 4, 1, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 4, 2, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 3, 4, 2, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 0, 1, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 0, 1, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 0, 2, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 0, 2, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 0, 3, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 0, 3, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 1, 0, 2, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 1, 0, 3, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 1, 2, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 1, 2, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 1, 3, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 1, 3, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 2, 0, 1, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 2, 0, 3, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 2, 1, 0, 3 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 2, 1, 3, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 2, 3, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 2, 3, 1, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 3, 0, 1, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 3, 0, 2, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 3, 1, 0, 2 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 3, 1, 2, 0 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 3, 2, 0, 1 }));
      list.add(Arrays.asList(new Integer[] { 5, 4, 3, 2, 1, 0 }));
      LIST.add(Collections.unmodifiableList(list));
    }
  }
}
