name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Define the release version'
        required: true
        type: string
      developmentVersion:
        description: 'Define the development version'
        required: true
        type: string
        default: '-SNAPSHOT'
      releaseBranch:
        description: 'Create or replace release branch'
        required: true
        type: boolean
        default: true

jobs:
  call-workflow:
    name: "Release"
    uses: grzhe/workflows/.github/workflows/release.yaml@main
    with:
      releaseVersion: ${{inputs.releaseVersion}}
      developmentVersion: ${{inputs.developmentVersion}}
      releaseBranch: ${{inputs.releaseBranch}}
    secrets: inherit
