name: Unit Tests
on: push
jobs:
  Tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: 'github'
      - name: Run Unit Tests
        run: mvn test -B
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
